# generated by datamodel-codegen:
#   filename:  application_architecture.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any

from pydantic import (
    AnyUrl,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    TypeAdapter,
    conint,
    constr,
)


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    AssetID: constr(pattern=r'^[a-zA-Z0-9]+$', min_length=1)
    version: constr(pattern=r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$')
    created: date


class AnchorString(RootModel[constr(pattern=r'^[A-Za-z_][-A-Za-z0-9._]*$')]):
    root: constr(pattern=r'^[A-Za-z_][-A-Za-z0-9._]*$')


class UriString(RootModel[AnyUrl]):
    root: AnyUrl


class UriReferenceString(RootModel[str]):
    root: str


class NonNegativeInteger(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class NonNegativeIntegerDefault0(RootModel[NonNegativeInteger]):
    root: NonNegativeInteger = Field(default_factory=lambda: NonNegativeInteger(0))


class SimpleTypes(Enum):
    array = 'array'
    boolean = 'boolean'
    integer = 'integer'
    null = 'null'
    number = 'number'
    object = 'object'
    string = 'string'


class StringArray(RootModel[list[str]]):
    root: list[str] = []


class MetaData1(BaseModel):
    title: str | None = None
    description: str | None = None
    default: Any | None = None
    deprecated: bool | None = False
    readOnly: bool | None = False
    writeOnly: bool | None = False
    examples: list[Any] | None = None


class MetaData(RootModel[MetaData1 | bool]):
    root: MetaData1 | bool = Field(..., title='Meta-data vocabulary meta-schema')


class FormatAnnotation1(BaseModel):
    format: str | None = None


class FormatAnnotation(RootModel[FormatAnnotation1 | bool]):
    root: FormatAnnotation1 | bool = Field(
        ..., title='Format vocabulary meta-schema for annotation results'
    )


class ControlDetail1(BaseModel):
    requirement_url: str = Field(
        ...,
        alias='requirement-url',
        description='The requirement schema that specifies how a control should be defined',
    )
    config_url: str = Field(
        ...,
        alias='config-url',
        description='The configuration of how the control requirement schema is met',
    )
    config: dict[str, Any] | None = Field(
        None,
        description='Inline configuration of how the control requirement schema is met',
    )


class ControlDetail2(BaseModel):
    requirement_url: str = Field(
        ...,
        alias='requirement-url',
        description='The requirement schema that specifies how a control should be defined',
    )
    config_url: str | None = Field(
        None,
        alias='config-url',
        description='The configuration of how the control requirement schema is met',
    )
    config: dict[str, Any] = Field(
        ...,
        description='Inline configuration of how the control requirement schema is met',
    )


class ControlDetail(RootModel[ControlDetail1 | ControlDetail2]):
    root: ControlDetail1 | ControlDetail2


class MetadataModel(RootModel[list[dict[str, Any]] | dict[str, Any]]):
    root: list[dict[str, Any]] | dict[str, Any]


class Details(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detailed_architecture: str | None = Field(None, alias='detailed-architecture')
    required_pattern: str | None = Field(None, alias='required-pattern')


class InterfaceDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unique_id: str = Field(
        ...,
        alias='unique-id',
        description='Unique identifier for this interface instance',
    )
    definition_url: str = Field(
        ...,
        alias='definition-url',
        description='URI of the external schema this interface configuration conforms to',
    )
    config: dict[str, Any] = Field(
        ...,
        description='Inline configuration conforming to the external interface schema',
    )


class InterfaceType(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    unique_id: str = Field(..., alias='unique-id')


class ComposedOfType(BaseModel):
    container: str
    nodes: list[str] = Field(..., min_length=1)


class NodeInterface(BaseModel):
    node: str
    interfaces: list[str] | None = None


class DeployedInType(BaseModel):
    container: str
    nodes: list[str] = Field(..., min_length=1)


class InteractsType(BaseModel):
    actor: str
    nodes: list[str] = Field(..., min_length=1)


class NodeTypeDefinition1(Enum):
    actor = 'actor'
    ecosystem = 'ecosystem'
    system = 'system'
    service = 'service'
    database = 'database'
    network = 'network'
    ldap = 'ldap'
    webclient = 'webclient'
    data_asset = 'data-asset'


class NodeTypeDefinition(RootModel[NodeTypeDefinition1 | str]):
    root: NodeTypeDefinition1 | str


class Protocol(Enum):
    HTTP = 'HTTP'
    HTTPS = 'HTTPS'
    FTP = 'FTP'
    SFTP = 'SFTP'
    JDBC = 'JDBC'
    WebSocket = 'WebSocket'
    SocketIO = 'SocketIO'
    LDAP = 'LDAP'
    AMQP = 'AMQP'
    TLS = 'TLS'
    mTLS = 'mTLS'
    TCP = 'TCP'


class Decision(BaseModel):
    description: str
    nodes: list[str]
    relationships: list[str]
    controls: list[str] | None = None


class Direction(Enum):
    source_to_destination = 'source-to-destination'
    destination_to_source = 'destination-to-source'


class Transition(BaseModel):
    relationship_unique_id: str = Field(
        ...,
        alias='relationship-unique-id',
        description='Unique identifier for the relationship in the architecture',
    )
    sequence_number: int = Field(
        ...,
        alias='sequence-number',
        description='Indicates the sequence of the relationship in the flow',
    )
    description: str = Field(
        ..., description='Functional summary of what is happening in the transition'
    )
    direction: Direction | None = 'source-to-destination'


class Validation1(BaseModel):
    type: SimpleTypes | list[SimpleTypes] | None = None
    const: Any | None = None
    enum: list[Any] | None = None
    multipleOf: PositiveFloat | None = None
    maximum: float | None = None
    exclusiveMaximum: float | None = None
    minimum: float | None = None
    exclusiveMinimum: float | None = None
    maxLength: NonNegativeInteger | None = None
    minLength: NonNegativeIntegerDefault0 | None = Field(
        default_factory=lambda: NonNegativeIntegerDefault0(0)
    )
    pattern: str | None = None
    maxItems: NonNegativeInteger | None = None
    minItems: NonNegativeIntegerDefault0 | None = Field(
        default_factory=lambda: NonNegativeIntegerDefault0(0)
    )
    uniqueItems: bool | None = False
    maxContains: NonNegativeInteger | None = None
    minContains: NonNegativeInteger | None = Field(
        default_factory=lambda: NonNegativeInteger(1)
    )
    maxProperties: NonNegativeInteger | None = None
    minProperties: NonNegativeIntegerDefault0 | None = Field(
        default_factory=lambda: NonNegativeIntegerDefault0(0)
    )
    required: StringArray | None = None
    dependentRequired: dict[str, StringArray] | None = None


class Validation(RootModel[Validation1 | bool]):
    root: Validation1 | bool = Field(..., title='Validation vocabulary meta-schema')


class Controls1(BaseModel):
    description: str = Field(
        ...,
        description='A description of a control and how it applies to a given architecture',
    )
    requirements: list[ControlDetail]


class Controls(RootModel[dict[constr(pattern=r'^[a-zA-Z0-9-]+$'), Controls1]]):
    root: dict[constr(pattern=r'^[a-zA-Z0-9-]+$'), Controls1]


class Flow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unique_id: str = Field(
        ..., alias='unique-id', description='Unique identifier for the flow'
    )
    name: str = Field(..., description='Descriptive name for the business flow')
    description: str = Field(
        ..., description="Detailed description of the flow's purpose"
    )
    requirement_url: str | None = Field(
        None,
        alias='requirement-url',
        description='Link to a detailed requirement document',
    )
    transitions: list[Transition] = Field(..., min_length=1)
    controls: Controls | None = None
    metadata: MetadataModel | None = None


class Node(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    unique_id: str = Field(..., alias='unique-id')
    node_type: NodeTypeDefinition = Field(..., alias='node-type')
    name: str
    description: str
    details: Details | None = None
    interfaces: list[InterfaceDefinition | InterfaceType] | None = None
    controls: Controls | None = None
    metadata: MetadataModel | None = None


class ConnectsType(BaseModel):
    source: NodeInterface
    destination: NodeInterface


class OptionType(RootModel[list[Decision]]):
    root: list[Decision]


class RelationshipType(BaseModel):
    interacts: InteractsType | None = None
    connects: ConnectsType | None = None
    deployed_in: DeployedInType = Field(..., alias='deployed-in')
    composed_of: ComposedOfType | None = Field(None, alias='composed-of')
    options: OptionType | None = None


class RelationshipType1(BaseModel):
    interacts: InteractsType | None = None
    connects: ConnectsType | None = None
    deployed_in: DeployedInType | None = Field(None, alias='deployed-in')
    composed_of: ComposedOfType = Field(..., alias='composed-of')
    options: OptionType | None = None


class RelationshipType2(BaseModel):
    interacts: InteractsType
    connects: ConnectsType | None = None
    deployed_in: DeployedInType | None = Field(None, alias='deployed-in')
    composed_of: ComposedOfType | None = Field(None, alias='composed-of')
    options: OptionType | None = None


class RelationshipType3(BaseModel):
    interacts: InteractsType | None = None
    connects: ConnectsType
    deployed_in: DeployedInType | None = Field(None, alias='deployed-in')
    composed_of: ComposedOfType | None = Field(None, alias='composed-of')
    options: OptionType | None = None


class RelationshipType4(BaseModel):
    interacts: InteractsType | None = None
    connects: ConnectsType | None = None
    deployed_in: DeployedInType | None = Field(None, alias='deployed-in')
    composed_of: ComposedOfType | None = Field(None, alias='composed-of')
    options: OptionType


class Relationship(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    unique_id: str = Field(..., alias='unique-id')
    description: str | None = None
    relationship_type: (
        RelationshipType
        | RelationshipType1
        | RelationshipType2
        | RelationshipType3
        | RelationshipType4
    ) = Field(..., alias='relationship-type')
    protocol: Protocol | None = None
    metadata: MetadataModel | None = None
    controls: Controls | None = None


class Core(BaseModel):
    nodes: list[Node] | None = None
    relationships: list[Relationship] | None = None
    metadata: MetadataModel | None = None
    controls: Controls | None = None
    flows: list[Flow] | None = None
    adrs: list[str] | None = Field(
        None,
        description='External links to ADRs (Architecture Decision Records) or similar documents that provide context or decisions related to the architecture. These can be URLs or references to internal documentation.',
    )
    additionalProperties: Any | None = None


class Core1(BaseModel):
    field_id: constr(pattern=r'^[^#]*#?$') | None = Field(None, alias='$id')
    field_schema: UriString | None = Field(None, alias='$schema')
    field_ref: UriReferenceString | None = Field(None, alias='$ref')
    field_anchor: AnchorString | None = Field(None, alias='$anchor')
    field_dynamicRef: UriReferenceString | None = Field(None, alias='$dynamicRef')
    field_dynamicAnchor: AnchorString | None = Field(None, alias='$dynamicAnchor')
    field_vocabulary: dict[UriString, bool] | None = Field(None, alias='$vocabulary')
    field_comment: str | None = Field(None, alias='$comment')
    field_defs: dict[str, CoreModel] | None = Field(None, alias='$defs')


class Applicator1(BaseModel):
    prefixItems: SchemaArray | None = None
    items: Applicator | None = None
    contains: Applicator | None = None
    additionalProperties: Applicator | None = None
    properties: dict[str, Applicator] | None = Field(default_factory=dict)
    patternProperties: dict[str, Applicator] | None = Field(default_factory=dict)
    dependentSchemas: dict[str, Applicator] | None = Field(default_factory=dict)
    propertyNames: Applicator | None = None
    if_: Applicator | None = Field(None, alias='if')
    then: Applicator | None = None
    else_: Applicator | None = Field(None, alias='else')
    allOf: SchemaArray | None = None
    anyOf: SchemaArray | None = None
    oneOf: SchemaArray | None = None
    not_: Applicator | None = Field(None, alias='not')


class Unevaluated1(BaseModel):
    unevaluatedItems: Unevaluated | None = None
    unevaluatedProperties: Unevaluated | None = None


class Content1(BaseModel):
    contentEncoding: str | None = None
    contentMediaType: str | None = None
    contentSchema: Content | None = None


class CoreModel(RootModel[Core1 | bool]):
    root: Core1 | bool = Field(..., title='Core vocabulary meta-schema')


class Applicator(RootModel[Applicator1 | bool]):
    root: Applicator1 | bool = Field(..., title='Applicator vocabulary meta-schema')


class Unevaluated(RootModel[Unevaluated1 | bool]):
    root: Unevaluated1 | bool = Field(
        ..., title='Unevaluated applicator vocabulary meta-schema'
    )


class Content(RootModel[Content1 | bool]):
    root: Content1 | bool = Field(..., title='Content vocabulary meta-schema')


class SchemaArray(RootModel[list[Applicator]]):
    root: list[Applicator] = Field(..., min_length=1)


class Schema(BaseModel):
    definitions: dict[str, Schema] | None = Field(default_factory=dict, deprecated=True)
    dependencies: dict[str, Schema | StringArray] | None = Field(
        default_factory=lambda: TypeAdapter(
            dict[str, Schema | StringArray]
        ).validate_python({}),
        deprecated=True,
    )
    field_recursiveAnchor: AnchorString | None = Field(
        None, alias='$recursiveAnchor', deprecated=True
    )
    field_recursiveRef: UriReferenceString | None = Field(
        None, alias='$recursiveRef', deprecated=True
    )


class Calm(Schema, Core):
    pass


class ApplicationArchitectureDocument(Calm):
    metadata: Metadata


Core1.model_rebuild()
Applicator1.model_rebuild()
Unevaluated1.model_rebuild()
Content1.model_rebuild()


from pydantic import field_validator, model_validator


class ApplicationArchitecture(ApplicationArchitectureDocument):
  model_config = ConfigDict(extra='forbid')

  @model_validator(mode='before')
  @classmethod
  def _validate_root_metadata_object(cls, data: Any) -> Any:
    if not isinstance(data, dict):
      return data

    metadata = data.get('metadata')
    if metadata is None:
      raise ValueError('metadata is required')
    if not isinstance(metadata, dict):
      raise ValueError('metadata must be an object')

    return data

  @field_validator('metadata')
  @classmethod
  def _validate_metadata(cls, value: Metadata) -> Metadata:
    if not value.AssetID.isalnum():
      raise ValueError('AssetID must contain only ASCII letters and digits')

    version_parts = value.version.split('.')
    if len(version_parts) != 3 or any(not part.isdigit() for part in version_parts):
      raise ValueError('version must use major.minor.patch semantic version format')

    if not isinstance(value.created, date):
      raise ValueError('created must be a valid calendar date')

    return value


__all__ = ['ApplicationArchitecture', 'ApplicationArchitectureDocument', 'Metadata']
