# generated by datamodel-codegen:
#   filename:  component_dependencies_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, constr

from . import dependency_edge


class ComponentDependenciesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: constr(min_length=1) = Field(..., alias='node-id')
    dependency_graph: list[dependency_edge.DependencyEdge] = Field(
        ..., alias='dependency-graph'
    )
