# generated by datamodel-codegen:
#   filename:  component_node.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, constr


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    parent_asset_id: constr(min_length=1) = Field(..., alias='parent-asset-id')


class ComponentInterface(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interface_local_id: constr(min_length=1) = Field(..., alias='interface-local-id')
    interface_type: constr(min_length=1) = Field(..., alias='interface-type')


class EndpointRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: constr(min_length=1) = Field(..., alias='node-id')
    interface_local_id: constr(min_length=1) = Field(..., alias='interface-local-id')


class ComponentRelationship(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    relationship_type: constr(min_length=1) = Field(..., alias='relationship-type')
    source: EndpointRef
    target: EndpointRef


class ComponentNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: constr(min_length=1) = Field(..., alias='node-id')
    node_type: constr(min_length=1) = Field(..., alias='node-type')
    node_name: constr(min_length=1) = Field(..., alias='node-name')
    metadata: Metadata
    interfaces: list[ComponentInterface] | None = None
    relationships: list[ComponentRelationship] | None = None
