# generated by datamodel-codegen:
#   filename:  component.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, constr


class Component(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    component_id: constr(min_length=1)
    name: constr(min_length=1)
    version: str | None = None
    metadata: dict[str, Any] | None = None
