# generated by datamodel-codegen:
#   filename:  component_dependencies_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, constr


class DependencyEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    relationship_type: constr(min_length=1) = Field(..., alias='relationship-type')
    source_node_id: constr(min_length=1) = Field(..., alias='source-node-id')
    target_node_id: constr(min_length=1) = Field(..., alias='target-node-id')
