# generated by datamodel-codegen:
#   filename:  health_response.schema.json
#   timestamp: 2026-03-15T01:48:39+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str
    service: str
    version: str
    time: AwareDatetime
