# generated by datamodel-codegen:
#   filename:  json_value.schema.json

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel


class JsonValue(RootModel[Any]):
    root: Any = Field(
        ...,
        description='Any valid JSON value (object, array, string, number, boolean, or null).',
        title='JsonValue',
    )
