# generated by datamodel-codegen:
#   filename:  deployment_scope_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import micro_affinity_group_deployment_step as deployment_step
from . import micro_affinity_group_deployment_edge as micro_ag_edge


class DeploymentSequence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bypassed_edges: list[micro_ag_edge.MicroAgEdge]
    steps: list[deployment_step.DeploymentStep] = Field(..., min_length=1)
