# generated by datamodel-codegen:
#   filename:  deployment_scope_response.schema.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr

from . import micro_affinity_group_deployment_sequence as deployment_sequence_1
from . import micro_affinity_group_deployment_edge as micro_ag_edge


class MicroAffinityGroupDeploymentScope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    micro_ag_id: constr(min_length=1)
    environment: constr(min_length=1)
    effective_date: AwareDatetime
    graph_has_cycles: bool
    dependency_graph: list[micro_ag_edge.MicroAgEdge]
    deployment_sequence: deployment_sequence_1.DeploymentSequence
