# generated by datamodel-codegen:
#   filename:  micro_affinity_group.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, constr


class MicroAffinityGroupWorkload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    asset_id: constr(min_length=1)


class MicroAffinityGroupDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    micro_ag_id: constr(min_length=1)
    name: constr(min_length=1) | None = None
    parent_asset_id: constr(min_length=1)
    architecture_version: constr(pattern=r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$')
    environment: constr(min_length=1)
    effective_date: constr(
        pattern=r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):[0-5]\d:[0-5]\dZ$'
    )
    workloads: list[MicroAffinityGroupWorkload] = Field(
        ...,
        description='Workload IDs must be unique within a request. Architecture lookup rules are enforced outside JSON Schema.',
        min_length=1,
    )


from pydantic import model_validator


class MicroAffinityGroup(MicroAffinityGroupDocument):
  @model_validator(mode='after')
  def _validate_unique_workload_ids(self) -> MicroAffinityGroup:
    seen: set[str] = set()
    duplicates: list[str] = []
    for workload in self.workloads:
      if workload.id in seen and workload.id not in duplicates:
        duplicates.append(workload.id)
      seen.add(workload.id)

    if duplicates:
      duplicate_list = ', '.join(sorted(duplicates))
      raise ValueError(f'workloads contain duplicate id values: {duplicate_list}')

    return self


__all__ = ['MicroAffinityGroup', 'MicroAffinityGroupDocument', 'MicroAffinityGroupWorkload']
