# generated by datamodel-codegen:
#   filename:  deployment_scope_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class MicroAgId(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class DeploymentStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step_index: conint(ge=1)
    micro_ag_ids: list[MicroAgId] = Field(..., min_length=1)
