# generated by datamodel-codegen:
#   filename:  deployment_scope_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, constr


class MicroAgEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_micro_ag_id: constr(min_length=1)
    destination_micro_ag_id: constr(min_length=1)
    is_cyclic: bool | None = None
