# generated by datamodel-codegen:
#   filename:  problem_details.schema.json
#   timestamp: 2026-03-15T01:48:39+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ProblemDetails(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: str
    title: str
    status: int
    detail: str
    error_code: str | None = None
    errors: dict[str, list[str]] | None = None
